# beautify json
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

# disable health check against config-server
health:
  config:
    enabled: false

logging:
  pattern:
    console: "%d{ABSOLUTE} %5p - %m%n"

logging.level.root: WARN
logging.level.org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
logging.level.com.epages: INFO
